#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tomado.Resource", IsApplication=true)]

namespace Tomado
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fab_scale_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fab_scale_up = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fab_slide_in_from_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fab_slide_in_from_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fab_slide_out_to_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fab_slide_out_to_right = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int fab_colorNormal = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorPressed = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorRipple = 2130771971;
			
			// aapt resource value: 0x7f01000d
			public const int fab_elevationCompat = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int fab_hideAnimation = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fab_label = 2130771980;
			
			// aapt resource value: 0x7f010012
			public const int fab_progress = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int fab_progress_backgroundColor = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int fab_progress_color = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int fab_progress_indeterminate = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int fab_progress_max = 2130771985;
			
			// aapt resource value: 0x7f010013
			public const int fab_progress_showBackground = 2130771987;
			
			// aapt resource value: 0x7f010005
			public const int fab_shadowColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fab_shadowRadius = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int fab_shadowXOffset = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadowYOffset = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int fab_showAnimation = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int fab_showShadow = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010027
			public const int menu_animationDelayPerItem = 2130772007;
			
			// aapt resource value: 0x7f010037
			public const int menu_backgroundColor = 2130772023;
			
			// aapt resource value: 0x7f010015
			public const int menu_buttonSpacing = 2130771989;
			
			// aapt resource value: 0x7f010028
			public const int menu_buttonToggleAnimation = 2130772008;
			
			// aapt resource value: 0x7f010033
			public const int menu_colorNormal = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int menu_colorPressed = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int menu_colorRipple = 2130772021;
			
			// aapt resource value: 0x7f01003a
			public const int menu_fab_hide_animation = 2130772026;
			
			// aapt resource value: 0x7f010038
			public const int menu_fab_label = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int menu_fab_show_animation = 2130772025;
			
			// aapt resource value: 0x7f01002c
			public const int menu_fab_size = 2130772012;
			
			// aapt resource value: 0x7f010026
			public const int menu_icon = 2130772006;
			
			// aapt resource value: 0x7f010022
			public const int menu_labels_colorNormal = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int menu_labels_colorPressed = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int menu_labels_colorRipple = 2130772004;
			
			// aapt resource value: 0x7f010020
			public const int menu_labels_cornerRadius = 2130772000;
			
			// aapt resource value: 0x7f01002e
			public const int menu_labels_customFont = 2130772014;
			
			// aapt resource value: 0x7f01002a
			public const int menu_labels_ellipsize = 2130772010;
			
			// aapt resource value: 0x7f010018
			public const int menu_labels_hideAnimation = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int menu_labels_margin = 2130771990;
			
			// aapt resource value: 0x7f01002b
			public const int menu_labels_maxLines = 2130772011;
			
			// aapt resource value: 0x7f01001d
			public const int menu_labels_padding = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int menu_labels_paddingBottom = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int menu_labels_paddingLeft = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int menu_labels_paddingRight = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int menu_labels_paddingTop = 2130771993;
			
			// aapt resource value: 0x7f010025
			public const int menu_labels_position = 2130772005;
			
			// aapt resource value: 0x7f010017
			public const int menu_labels_showAnimation = 2130771991;
			
			// aapt resource value: 0x7f010021
			public const int menu_labels_showShadow = 2130772001;
			
			// aapt resource value: 0x7f010029
			public const int menu_labels_singleLine = 2130772009;
			
			// aapt resource value: 0x7f01002d
			public const int menu_labels_style = 2130772013;
			
			// aapt resource value: 0x7f01001e
			public const int menu_labels_textColor = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int menu_labels_textSize = 2130771999;
			
			// aapt resource value: 0x7f010036
			public const int menu_openDirection = 2130772022;
			
			// aapt resource value: 0x7f01002f
			public const int menu_shadowColor = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int menu_shadowRadius = 2130772016;
			
			// aapt resource value: 0x7f010031
			public const int menu_shadowXOffset = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int menu_shadowYOffset = 2130772018;
			
			// aapt resource value: 0x7f010014
			public const int menu_showShadow = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int base_app_color = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int fab_size_mini = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fab_size_normal = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int labels_text_size = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_add_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_delete_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_search_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060019
			public const int SessionsListItemLayout = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int SwipeRefreshLayout_Sessions = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int Timer_MainLayout = 2131099681;
			
			// aapt resource value: 0x7f060017
			public const int buttonCancel_NewSession = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int buttonDeleteSession = 2131099676;
			
			// aapt resource value: 0x7f060027
			public const int buttonFinish = 2131099687;
			
			// aapt resource value: 0x7f06000e
			public const int buttonOK_congrats = 2131099662;
			
			// aapt resource value: 0x7f060026
			public const int buttonPause = 2131099686;
			
			// aapt resource value: 0x7f060018
			public const int buttonSave_NewSession = 2131099672;
			
			// aapt resource value: 0x7f060025
			public const int buttonWork = 2131099685;
			
			// aapt resource value: 0x7f06000a
			public const int down = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int editTextDate_NewSession = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int editTextTime_NewSession = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int editTextTitle_NewSession = 2131099667;
			
			// aapt resource value: 0x7f060005
			public const int end = 2131099653;
			
			// aapt resource value: 0x7f06001b
			public const int evTime = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int evTitle = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int fab_label = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int freeTimeListItem = 2131099664;
			
			// aapt resource value: 0x7f060003
			public const int left = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout1 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int listViewFreeTimeSessions = 2131099663;
			
			// aapt resource value: 0x7f06001e
			public const int listViewSessions = 2131099678;
			
			// aapt resource value: 0x7f060006
			public const int marquee = 2131099654;
			
			// aapt resource value: 0x7f06001f
			public const int menu_newSession = 2131099679;
			
			// aapt resource value: 0x7f060007
			public const int middle = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int mini = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int none = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int normal = 2131099650;
			
			// aapt resource value: 0x7f060024
			public const int relativeLayout1 = 2131099684;
			
			// aapt resource value: 0x7f060004
			public const int right = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int start = 2131099657;
			
			// aapt resource value: 0x7f060016
			public const int switchRecurring = 2131099670;
			
			// aapt resource value: 0x7f06000c
			public const int textViewCongratulationsMessage = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int textViewDuration = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int textViewTime = 2131099665;
			
			// aapt resource value: 0x7f060023
			public const int textViewTimer = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int textViewTimerTitle = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int up = 2131099659;
			
			// aapt resource value: 0x7f060020
			public const int viewPager = 2131099680;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonOverlay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CongratulationsDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FreeTimeDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FreeTimeListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewSession = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SessionListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Sessions = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SwipeLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Timer = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ButtonText_pause = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int ButtonText_work = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Finished = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int PackageName = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int DialogContentEditText = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int DialogContentTextView = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorNormal = 0;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorPressed = 1;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 13
			public const int FloatingActionButton_fab_elevationCompat = 13;
			
			// aapt resource value: 11
			public const int FloatingActionButton_fab_hideAnimation = 11;
			
			// aapt resource value: 12
			public const int FloatingActionButton_fab_label = 12;
			
			// aapt resource value: 18
			public const int FloatingActionButton_fab_progress = 18;
			
			// aapt resource value: 15
			public const int FloatingActionButton_fab_progress_backgroundColor = 15;
			
			// aapt resource value: 14
			public const int FloatingActionButton_fab_progress_color = 14;
			
			// aapt resource value: 16
			public const int FloatingActionButton_fab_progress_indeterminate = 16;
			
			// aapt resource value: 17
			public const int FloatingActionButton_fab_progress_max = 17;
			
			// aapt resource value: 19
			public const int FloatingActionButton_fab_progress_showBackground = 19;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_shadowColor = 5;
			
			// aapt resource value: 6
			public const int FloatingActionButton_fab_shadowRadius = 6;
			
			// aapt resource value: 7
			public const int FloatingActionButton_fab_shadowXOffset = 7;
			
			// aapt resource value: 8
			public const int FloatingActionButton_fab_shadowYOffset = 8;
			
			// aapt resource value: 10
			public const int FloatingActionButton_fab_showAnimation = 10;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_showShadow = 4;
			
			// aapt resource value: 9
			public const int FloatingActionButton_fab_size = 9;
			
			public static int[] FloatingActionMenu = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026};
			
			// aapt resource value: 19
			public const int FloatingActionMenu_menu_animationDelayPerItem = 19;
			
			// aapt resource value: 35
			public const int FloatingActionMenu_menu_backgroundColor = 35;
			
			// aapt resource value: 1
			public const int FloatingActionMenu_menu_buttonSpacing = 1;
			
			// aapt resource value: 20
			public const int FloatingActionMenu_menu_buttonToggleAnimation = 20;
			
			// aapt resource value: 31
			public const int FloatingActionMenu_menu_colorNormal = 31;
			
			// aapt resource value: 32
			public const int FloatingActionMenu_menu_colorPressed = 32;
			
			// aapt resource value: 33
			public const int FloatingActionMenu_menu_colorRipple = 33;
			
			// aapt resource value: 38
			public const int FloatingActionMenu_menu_fab_hide_animation = 38;
			
			// aapt resource value: 36
			public const int FloatingActionMenu_menu_fab_label = 36;
			
			// aapt resource value: 37
			public const int FloatingActionMenu_menu_fab_show_animation = 37;
			
			// aapt resource value: 24
			public const int FloatingActionMenu_menu_fab_size = 24;
			
			// aapt resource value: 18
			public const int FloatingActionMenu_menu_icon = 18;
			
			// aapt resource value: 14
			public const int FloatingActionMenu_menu_labels_colorNormal = 14;
			
			// aapt resource value: 15
			public const int FloatingActionMenu_menu_labels_colorPressed = 15;
			
			// aapt resource value: 16
			public const int FloatingActionMenu_menu_labels_colorRipple = 16;
			
			// aapt resource value: 12
			public const int FloatingActionMenu_menu_labels_cornerRadius = 12;
			
			// aapt resource value: 26
			public const int FloatingActionMenu_menu_labels_customFont = 26;
			
			// aapt resource value: 22
			public const int FloatingActionMenu_menu_labels_ellipsize = 22;
			
			// aapt resource value: 4
			public const int FloatingActionMenu_menu_labels_hideAnimation = 4;
			
			// aapt resource value: 2
			public const int FloatingActionMenu_menu_labels_margin = 2;
			
			// aapt resource value: 23
			public const int FloatingActionMenu_menu_labels_maxLines = 23;
			
			// aapt resource value: 9
			public const int FloatingActionMenu_menu_labels_padding = 9;
			
			// aapt resource value: 8
			public const int FloatingActionMenu_menu_labels_paddingBottom = 8;
			
			// aapt resource value: 6
			public const int FloatingActionMenu_menu_labels_paddingLeft = 6;
			
			// aapt resource value: 7
			public const int FloatingActionMenu_menu_labels_paddingRight = 7;
			
			// aapt resource value: 5
			public const int FloatingActionMenu_menu_labels_paddingTop = 5;
			
			// aapt resource value: 17
			public const int FloatingActionMenu_menu_labels_position = 17;
			
			// aapt resource value: 3
			public const int FloatingActionMenu_menu_labels_showAnimation = 3;
			
			// aapt resource value: 13
			public const int FloatingActionMenu_menu_labels_showShadow = 13;
			
			// aapt resource value: 21
			public const int FloatingActionMenu_menu_labels_singleLine = 21;
			
			// aapt resource value: 25
			public const int FloatingActionMenu_menu_labels_style = 25;
			
			// aapt resource value: 10
			public const int FloatingActionMenu_menu_labels_textColor = 10;
			
			// aapt resource value: 11
			public const int FloatingActionMenu_menu_labels_textSize = 11;
			
			// aapt resource value: 34
			public const int FloatingActionMenu_menu_openDirection = 34;
			
			// aapt resource value: 27
			public const int FloatingActionMenu_menu_shadowColor = 27;
			
			// aapt resource value: 28
			public const int FloatingActionMenu_menu_shadowRadius = 28;
			
			// aapt resource value: 29
			public const int FloatingActionMenu_menu_shadowXOffset = 29;
			
			// aapt resource value: 30
			public const int FloatingActionMenu_menu_shadowYOffset = 30;
			
			// aapt resource value: 0
			public const int FloatingActionMenu_menu_showShadow = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
