#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tomado.Resource", IsApplication=true)]

namespace Tomado
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int Timer_MainLayout = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int buttonNewSession = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int buttonPause = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int buttonSave_NewSession = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int buttonWork = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int editTextDate_NewSession = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int editTextTime_NewSession = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int editTextTitle_NewSession = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int evEnd = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int evStart = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int evTitle = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int listViewSessions = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int relativeLayout1 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int textViewTimer = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int textViewTimerType = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int viewPager = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int NewSession = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SessionListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Sessions = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SwipeLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Timer = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ButtonText_pause = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ButtonText_work = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Finished = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
